# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(262525)
$foreground = rgb(FCF9F9)
$color0 = rgb(4C4A4B)
$color1 = rgb(42170D)
$color2 = rgb(641314)
$color3 = rgb(A70C0B)
$color4 = rgb(685255)
$color5 = rgb(BB0B09)
$color6 = rgb(B8B3B2)
$color7 = rgb(F2EEEE)
$color8 = rgb(A9A7A6)
$color9 = rgb(581E11)
$color10 = rgb(851A1B)
$color11 = rgb(DF110F)
$color12 = rgb(8A6D71)
$color13 = rgb(F90E0C)
$color14 = rgb(F6EEED)
$color15 = rgb(F2EEEE)
