# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F221F)
$foreground = rgb(EDDEC6)
$color0 = rgb(454845)
$color1 = rgb(4C4E37)
$color2 = rgb(515138)
$color3 = rgb(3D5464)
$color4 = rgb(806B41)
$color5 = rgb(6A7E8B)
$color6 = rgb(987945)
$color7 = rgb(DDC7A5)
$color8 = rgb(9A8C73)
$color9 = rgb(65684A)
$color10 = rgb(6B6C4B)
$color11 = rgb(517085)
$color12 = rgb(AB8F56)
$color13 = rgb(8DA8B9)
$color14 = rgb(CBA15C)
$color15 = rgb(DDC7A5)
