# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161815)
$foreground = rgb(F1F2EF)
$color0 = rgb(3D3F3C)
$color1 = rgb(3D4A46)
$color2 = rgb(526977)
$color3 = rgb(656D69)
$color4 = rgb(80683E)
$color5 = rgb(9B9D98)
$color6 = rgb(A2A29D)
$color7 = rgb(E3E3E0)
$color8 = rgb(9F9F9D)
$color9 = rgb(51635E)
$color10 = rgb(6D8C9F)
$color11 = rgb(87928C)
$color12 = rgb(AA8B52)
$color13 = rgb(CED1CA)
$color14 = rgb(D7D9D2)
$color15 = rgb(E3E3E0)
