add_newline = false
command_timeout = 1000

format = """
$os\
$hostname\
$username\
$sudo\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$docker_context\
$kubernetes\
$rust\
$golang\
$python\
$nodejs\
$lua\
$solidity\
$dotnet\
$shell\
$cmd_duration $jobs $time\
$line_break\
$character\
"""

[os]
format = '[$symbol](bold bright-white)  '
disabled = false

[os.symbols]
Windows = ''
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[.$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold bright-black)'
disabled = false

[docker_context]
symbol = "󰡨"
format = '[$symbol ($version )]($style)'
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[kubernetes]
symbol = "☸"
format = '[$symbol $context( \($namespace\))]($style) '
detect_files = ["k8s", "skaffold.yaml"]
detect_folders = [".kube"]

[rust]
symbol = ""
format = '[$symbol ($version )]($style)'
detect_files = ["Cargo.toml", "Cargo.lock"]

[golang]
symbol = ""
format = '[$symbol ($version )]($style)'
detect_files = ["go.mod", "go.sum", "glide.yaml", "Gopkg.yml", "Gopkg.lock", ".go-version"]

[python]
symbol = "󰌠"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", "setup.py", "setup.cfg", "tox.ini", ".python-version"]

[lua]
symbol = ""
format = '[$symbol ($version )]($style)'
detect_files = ["?.lua", ".lua-version", ".luacheckrc"]

[shell]
format = "[$indicator]($style) "
disabled = false

[solidity]
symbol = "◆"
format = '[$symbol ($version )]($style)'
detect_files = ["*.sol"]
detect_extensions = ["sol"]

[nodejs]
symbol = ""
format = "[$symbol ($version )]($style)"
detect_files = ["package.json", ".nvmrc", ".node-version"]

[dotnet]
symbol = "󰪮"
format = '[$symbol ($version )(🎯 $tfm )]($style)'
detect_files = ["project.json", "global.json", "paket.dependencies", "*.csproj", "*.fsproj", "*.xproj"]

[fill]
symbol = " "

[sudo]
format = "[$symbol]($style)"
style = "italic bright-purple"
symbol = "◇┈"
disabled = false

[directory]
truncation_length = 1
truncation_symbol = '…/'
# home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = '[󰋜 ~ $path]($style)[$read_only]($read_only_style) '

[character]
success_symbol = "[\\$](bold bright-green)"
# success_symbol = "[ ⤷](bold bright-white)"
# success_symbol = "[ ↬](bold bright-white)"
# error_symbol = "[❯](bold bright-red)"
error_symbol = "[ ↳](bold bright-red)"
# success_symbol = ' '
# error_symbol = ' '
vimcmd_symbol = "[<](bold green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold cyan'
conflicted = '[ ${count}](bright-red) '                     # confliced
up_to_date = '[󰘽](bright-green) '                            # up-to-date
untracked = '[󰋗 ${count}](red) '                             # untracked
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 ${count}](yellow) '                           # modified
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[time]
disabled = false
style = "bold bright-yellow"
format = "[ $time ]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
